### PR TITLE
Added New Caseflow Support Tech

### PR DESCRIPTION
**Pull request by msj0nes**
Added new Caseflow Support Tech - Raju Sharma VACOSHARMR

### CODE REVIEW

**Review by pkarman — APPROVED** [review]
lgtm

**Comment by msj0nes** [comment]
@pkarman any idea why this failed and how I can resolve it

**Comment by pkarman** [comment]
ugh. looks like this app needs a Rails upgrade to fix security problems.

**Comment by pkarman** [comment]
@msj0nes should be ok now.

**Pull request merged**
