### PR TITLE
Adds contact email

### LINKED ISSUE #16: User should be able to manually enter "contact email" field on feedback form
As a Feedback user, I want to be able to manually enter in a contact email.

### Acceptance Criteria
1. Verify that the Contact Email field is above the main contact field for the Feedback form.
1. Verify that the email is saved on the Feedback. (This may require #6 for verification)

@shanear @lakohl — @shellicious pointed out that many ROs seem to use shared logins for certification. In light of that fact, do you think that we should capture both the username coming in and allow users to optionally enter a contact email? 

### Sub-Tasks

- [ ] QA discovery and scripting.

### PR DESCRIPTION
**Pull request by amprokop**
Adds contact email to feedback form, changes "Cancel" to link from button as per request from @shellicious 

Fixes #16 

Testing:
UI works (we'll probably move some of this stuff around), rake passes
image

### CODE REVIEW

**Review by nemodjuric — CHANGES_REQUESTED** [review]
We should validate email input preventing user from entering non-valid string. 
I.e in feedback.rb.
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

**Comment by msknee** [comment]
UI tweaks for @nemodjuric and @amprokop : 
- free text field for entering feedback should be the same width as the contact email field
- the cancel link and submit button should be below the white container, like so:

screen shot 2016-11-28 at 4 15 18 pm

**Comment by amprokop** [comment]
@shellicious — i moved the cancel link. can you make an issue for the width issue? also, is that what you really want? it's gonna be kinda comically wide for an email field

**Comment by amprokop** [comment]
@nemodjuric — i added validation just for `@` — that should cover most cases without making it too complicated. should be fine i think.

**Comment by msknee** [comment]
thanks for moving the cancel link @amprokop! And the feedback button too? 

I meant the width of the feedback box should be decreased to be the same as the width of the email field. Will make a separate issue. Width might be subject to over the next few weeks due to work being done to standardize the width of containers throughout Caseflow.

**Comment by amprokop** [comment]
yeah, i moved both down @shellicious. thanks for clarifying.

**Review by nemodjuric — APPROVED** [review]

**Pull request merged**
