### PR TITLE
Feedback style tweaks

### PR DESCRIPTION
**Pull request by mmlumba**
caseflow feedback

Connects #148

### CODE REVIEW

**Comment by mmlumba** [comment]
@shellicious Please validate the above screenshot

**Comment by amprokop** [comment]
@shellicious, can you review the screenshot and determine if it's ok?

**Comment by msknee** [comment]
I suggest having a separate label for the first box that is 1 line long: "Add your comments -- please leave PII out". 

The "What's working well? ... improve Caseflow for everyone" blurb should be in a separate paragraph above the first box and its labels.

**Comment by mmlumba** [comment]
@shellicious Updating AC and making the changes per your feedback
caseflow feedback3

**Comment by amprokop** [comment]
Sorry for the runaround @mmlumba — @shellicious and i discussed this. Here's the content we agreed on:

Heading: Tell us about your experience with Caseflow.

Paragraph: What’s working well? What’s not working? Your comments will help us improve Caseflow for everyone.

Field Label: Add your comments here. Please don’t put PII in this field.

**Comment by msknee** [comment]
Hmm, it looks like "Add your comments here. Please don’t put PII in this field." doesn't quite fit in 1 line. Can we trim it down to:

"Add your comments. Please don’t put PII here."

**Comment by mmlumba** [comment]
New screenshot:
screen shot 2017-10-23 at 9 57 19 am

**Comment by amprokop** [comment]
@mmlumba — is the new label a darker shade of black than everything else here?

**Comment by mmlumba** [comment]
@amprokop changed the color so that it matches the rest of the label text

**Comment by amprokop** [comment]
@mmlumba can you take a screenshot? thanks!

**Comment by mmlumba** [comment]
@amprokop @shellicious 
screen shot 2017-10-23 at 4 13 53 pm

**Review by amprokop — APPROVED** [review]

**Pull request merged**
