### PR TITLE
Added Cancel button.

### PR DESCRIPTION
**Pull request by nemodjuric**
screen shot 2016-11-21 at 12 38 52 pm

### CODE REVIEW

**Comment by amprokop** [comment]
hey @nemodjuric — can you add a screenshot of what this looks like in the PR request body?

**Comment by nemodjuric** [comment]
screen shot 2016-11-21 at 12 38 52 pm

**Comment by amprokop** [comment]
cool — in the future, can you put these screenshots in the description of the PR? It helps a lot when reviewing UX changes.
Am i seeing that the cancel button isn't aligned with the Send Feedback button? What's up with that?

**Comment by nemodjuric** [comment]
screen shot 2016-11-21 at 1 28 29 pm
Fixed non-alignment.

**Pull request merged**
