### PR TITLE
#74  Admin | Dashboard | Add "Current Feedback" as header

### PR DESCRIPTION
**Pull request by ariperez-gov**
Connects to #74

### CODE REVIEW

**Comment by ariperez-gov** [comment]
Only weird one about this one is that I had to use a `<h2>` vs `<h1>` or else I got the following:
image

**Comment by ariperez-gov** [comment]
Also bumped `rubyzip` inside the gemlock to address a security audit issue that was failing Travis.

**Comment by amprokop** [comment]
Looks good. Yeah, Sniffybara gets a bit uptight about header tags. Best to just comply :)

**Review by amprokop — APPROVED** [review]
LGTM

**Pull request merged**
